// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: insert_documents.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const insertUploadedDocument = `-- name: InsertUploadedDocument :exec
INSERT INTO documents (
  id,
  s3_file,
  file_name,
  title,
  created_at,
  has_duplicate
) VALUES ($1, $2, $3, $4, NOW(), false)
`

type InsertUploadedDocumentParams struct {
	ID       uuid.UUID
	S3File   string
	FileName string
	Title    string
}

func (q *Queries) InsertUploadedDocument(ctx context.Context, arg InsertUploadedDocumentParams) error {
	_, err := q.db.ExecContext(ctx, insertUploadedDocument,
		arg.ID,
		arg.S3File,
		arg.FileName,
		arg.Title,
	)
	return err
}
