// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: search_region.sql

package db

import (
	"context"
	"database/sql"
)

const searchRegionsByNamePrefix = `-- name: SearchRegionsByNamePrefix :many
SELECT
    id,
    name
FROM
    regions
WHERE
    name ILIKE $1 || '%'
ORDER BY
    name
    LIMIT 10
`

func (q *Queries) SearchRegionsByNamePrefix(ctx context.Context, dollar_1 sql.NullString) ([]Region, error) {
	rows, err := q.db.QueryContext(ctx, searchRegionsByNamePrefix, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Region
	for rows.Next() {
		var i Region
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
