// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: search_keyword.sql

package db

import (
	"context"
	"database/sql"
)

const searchKeywordsByNamePrefix = `-- name: SearchKeywordsByNamePrefix :many
SELECT
    id,
    name
FROM
    keywords
WHERE
    name ILIKE $1 || '%'
ORDER BY
    name
    LIMIT 10
`

func (q *Queries) SearchKeywordsByNamePrefix(ctx context.Context, dollar_1 sql.NullString) ([]Keyword, error) {
	rows, err := q.db.QueryContext(ctx, searchKeywordsByNamePrefix, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Keyword
	for rows.Next() {
		var i Keyword
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
