root = "."
tmp_dir = "tmp"

[build]
bin = "./tmp/main"
cmd = "./tailwindcss -i static/css/input.css -o static/css/output.css && go build -o ./tmp/main main.go"
exclude_dir = ["tmp"]
include_dir = ["cmd", "views", "static", "models", "routes", "handlers", "db"]
include_ext = ["go", "html"]
stop_on_error = true

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
keep_scroll = true
