root = "."
tmp_dir = "tmp"

[build]
bin = "./tmp/main"
cmd = "./tools/tailwindcss -i web/assets/css/input.css -o web/assets/css/output.css && templ generate && go build -o ./tmp/main cmd/app/main.go"
exclude_dir = ["tmp", "web/assets", "web/components", "web/components/*.go"]
include_dir = ["cmd", "web", "pkg", "internal", "routes"]
include_ext = ["go", "templ"]

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
keep_scroll = true
