version: "2"

run:
  timeout: 5m

linters:
  enable:
    - revive
    - govet
  settings:
    revive:
      rules:
        - name: exported
          disabled: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
