// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Author struct {
	ID   uuid.UUID
	Name string
}

type Category struct {
	ID   uuid.UUID
	Name string
}

type DocAuthor struct {
	ID       uuid.UUID
	DocID    uuid.NullUUID
	AuthorID uuid.NullUUID
}

type DocCategory struct {
	ID         uuid.UUID
	DocID      uuid.NullUUID
	CategoryID uuid.NullUUID
}

type DocKeyword struct {
	ID        uuid.UUID
	DocID     uuid.NullUUID
	KeywordID uuid.NullUUID
}

type DocRegion struct {
	ID       uuid.UUID
	DocID    uuid.NullUUID
	RegionID uuid.NullUUID
}

type Document struct {
	ID              uuid.UUID
	FileName        string
	Title           string
	Abstract        sql.NullString
	PublishDate     sql.NullTime
	Source          sql.NullString
	IndexedByKendra sql.NullBool
	S3File          string
	S3FilePreview   sql.NullString
	PdfLink         sql.NullString
	CreatedAt       sql.NullTime
	DeletedAt       sql.NullTime
}

type Keyword struct {
	ID      uuid.UUID
	Keyword string
}

type Region struct {
	ID   uuid.UUID
	Name string
}
