name: Build and Test

on:
  pull_request:

jobs:
  build-test:
    name: Test Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y golang postgresql-client
          
      - name: Generate SQLC code (using existing schema.sql)
        run: |
          make install-all-linux
          export PATH=$PATH:$HOME/go/bin
          sqlc generate
      
      - name: Run Backend Unit Tests
        run: |
          go test -v ./pkg/db/handlers/...

      - name: Build and Test
        run: |
          ./tools/tailwindcss -i ./web/assets/css/input.css -o ./web/assets/css/output.css --minify
          templ generate
          go build -o gmu -buildvcs=false ./cmd/app/main.go
          

