name: Deploy to EC2

on:
  push:
    branches:
      - main
      - deploy-app
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        run: |
          sudo apt-get update
          sudo apt-get install -y golang-go
          
      - name: Add Go to PATH
        run: |
          echo "export PATH=$PATH:/usr/local/go/bin" >> ~/.bashrc
          source ~/.bashrc

      - name: Run deploy.sh on AWS EC2 server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          script: /home/ubuntu/deploy.sh
          debug: true 