name: Deploy

on:
  push:
    branches:
      - main
      - fix-deploy-issues

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run deploy.sh on AWS EC2 server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          envs: DB_HOST,DB_USER,DB_NAME,DB_PASSWORD
          script: |
            cd /var/www/go-htmx-app
            git stash
            git pull origin main

            # Install Go if not present
            if ! command -v go &> /dev/null; then
              echo "Installing Go..."
              curl -LO https://golang.org/dl/go1.22.2.linux-amd64.tar.gz
              sudo rm -rf /usr/local/go
              sudo tar -C /usr/local -xzf go1.22.2.linux-amd64.tar.gz
              export PATH=$PATH:/usr/local/go/bin
              echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.bashrc
            else
              echo "Go is already installed: $(go version)"
            fi

            # Install Flyway if not present
            if ! command -v flyway &> /dev/null; then
              wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/11.6.0/flyway-commandline-11.6.0-linux-x64.tar.gz | tar xvz
              sudo mv flyway-11.6.0 /opt/flyway
              sudo ln -s /opt/flyway/flyway /usr/local/bin/flyway
            fi

            echo "Installing SQLC and running database migrations"
            make install-all-linux
            export PATH=$PATH:/usr/local/go/bin
            chmod +x scripts/migrate_and_generate.sh
            ./scripts/migrate_and_generate.sh

            echo "Running tests..."
            go test -v ./pkg/db/handlers/...

            echo "Building application..."
            ./tools/tailwindcss -i ./web/assets/css/input.css -o ./web/assets/css/output.css --minify
            templ generate
            go build -o gmu -buildvcs=false ./cmd/app/main.go

            echo "Restarting application..."
            sudo systemctl restart goapp
