name: Build and Run Go + HTMX App

on:
  push:
    branches:
      - main
      - deploy-app
  pull_request:
    branches:
      - main
      - deploy-app

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: 🛎 Checkout Code
        uses: actions/checkout@v3

      - name: ⚙️ Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.3'  

      - name: 📦 Install Dependencies
        run: go mod tidy

      - name: 🛠 Install Tailwind and Air
        run: make install-tailwind-linux install-air

      - name: 🔧 Fix Permissions for Tailwind Binary
        run: chmod +x ./tailwindcss

      - name: 🚀 Run Air (Go Live Reload)
        run: air
