name: Deploy to EC2

on:
  push:
    branches:
      - main
      - deploy-app
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run deploy.sh on AWS EC2 server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          script: |
            source ~/.profile
            source ~/.bashrc
            export PATH=$PATH:/usr/local/go/bin
            cd /var/www/go-htmx-app
            git pull origin main
            go build -o gmu -buildvcs=false
            ./tailwindcss -i ./static/css/input.css -o ./static/css/output.css --minify
            sudo systemctl restart goapp
    
