name: Deploy Go + HTMX App to AWS EC2

on:
  push:
    branches:
      - main
      - deploy-app
  pull_request:
    branches:
      - main
      - deploy-app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.3'

      - name: Create .env file
        run: |
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "REGION=${{ secrets.REGION }}" >> .env
          echo "ACCESS_KEY=${{ secrets.ACCESS_KEY }}" >> .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "INDEX_ID=${{ secrets.INDEX_ID }}" >> .env

      - name: Install Dependencies
        run: go mod tidy

      - name: Install Tailwind and Air
        run: make install-tailwind-linux install-air

      - name: Build Go App
        run: go build -o gmu .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gmu-artifact
          path: |
            gmu
            .env

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: gmu-artifact
          path: build-files

      - name: SCP files to AWS EC2 server
        uses: appleboy/scp-action@master
        with:
          debug: true
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          source: "build-files/*"
          target: "/home/ubuntu/github-actions/build-files/"
          rm: true

      - name: Run deploy.sh on AWS EC2 server
        uses: appleboy/ssh-action@master
        with:
          debug: true
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          script: /home/ubuntu/deploy.sh
