name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - db-infrastructure
  pull_request:

jobs:
  build-test:
    name: Test Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y golang
          
      - name: Generate SQLC code
        run: |
          go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
          export PATH=$HOME/go/bin:/usr/local/go/bin:$PATH
          sqlc generate

      - name: Build and Test
        run: |
          make install-linux
          go build -o gmu -buildvcs=false
          ./tailwindcss -i ./static/css/input.css -o ./static/css/output.css --minify

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: build-test
    if: github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run deploy.sh on AWS EC2 server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          script: |
            export PATH=$HOME/go/bin:/usr/local/go/bin:$PATH
            cd /var/www/go-htmx-app
            git stash
            git pull origin main
            go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
            echo "$HOME/go/bin" >> $GITHUB_PATH
            sqlc generate
            make install-linux
            ./tailwindcss -i ./static/css/input.css -o ./static/css/output.css --minify
            go build -o gmu -buildvcs=false
            sudo systemctl restart goapp
