name: Kendra Document Indexing

on:
  schedule:
    # Run at 8 AM UTC (adjust time as needed)
    - cron: '0 8 * * *'
  push:
    branches:
      - batch-put # Change this to your specific branch name

jobs:
  index-documents:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Create .env file
        run: |
          cat << EOF > scripts/.env
          ROLE_ARN=${{ secrets.AWS_ROLE_ARN }}
          INDEX_ID=${{ secrets.AWS_INDEX_ID }}
          DB_HOST=${{ secrets.DB_HOST }}
          DB_USER=${{ secrets.DB_USER }}
          DB_NAME=${{ secrets.DB_NAME }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          EOF

      - name: Run indexing script
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          INDEX_ID: ${{ secrets.INDEX_ID }}
          ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
        run: python scripts/batchput.py

      - name: Check indexing status
        run: |
          echo "Checking Kendra indexing status..."
          # Get the list of documents being indexed
          aws kendra list-data-sources --index-id ${{ secrets.INDEX_ID }} --query "Status=SYNCING" --output json
          
          # Get sync status
          aws kendra describe-index --index-id ${{ secrets.INDEX_ID }} --output json
          
          echo "Note: Full indexing may take several hours. Check the Kendra console for detailed status." 