name: Lint

on:
  workflow_call:
    inputs:
      go-version:
        description: "Go version to use"
        required: false
        type: string
        default: "1.24"

jobs:
  lint:
    name: Lint Go Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5 # check version
        with:
          go-version: ${{ inputs.go-version }}
          cache: true

      - name: Lint Go Code with golangci-lint
        uses: golangci/golangci-lint-action@v8 # check version
        with:
          version: v2.1
          args: --verbose ./...
