name: Test AWS Credentials

on:
  push:
    branches:
      - batch-put
  workflow_dispatch:  # Keep manual triggering as an option

jobs:
  test-credentials:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Test AWS credentials
        run: |
          echo "Testing AWS credentials..."
          aws sts get-caller-identity
          echo "If you see your AWS account ID above, the credentials are working!"
          
          # Test Kendra access
          echo "Testing Kendra access..."
          aws kendra list-indices
          echo "If you see a list of Kendra indices, Kendra access is working!"
          
          # Test S3 access
          echo "Testing S3 access..."
          aws s3 ls
          echo "If you see a list of S3 buckets, S3 access is working!" 